# Generated by Django 4.1.6 on 2023-02-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdateapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='content',
        ),
    ]
