# Generated by Django 4.1.6 on 2023-02-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdateapi', '0002_rename_description_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petinterest',
            old_name='interest',
            new_name='pet_interest',
        ),
    ]
