# Generated by Django 4.1.6 on 2023-02-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdateapi', '0003_rename_interest_petinterest_pet_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pettrait',
            old_name='trait',
            new_name='pet_trait',
        ),
    ]
