# Generated by Django 4.1.6 on 2023-02-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playdateapi', '0004_rename_trait_pettrait_pet_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='leskeyes', max_length=50),
        ),
    ]
