# Generated by Django 4.1.6 on 2023-02-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playdateapi', '0005_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
