# Generated by Django 4.1.6 on 2023-03-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playdateapi', '0006_alter_user_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to='playdateapi.user')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uiser_two', to='playdateapi.user')),
            ],
        ),
    ]
